"""Train the two-head CRNN (intent head + slot head).

Run from the repo root:   python src/train.py
Loss = CrossEntropy(intent) + CrossEntropy(slot). The logged "acc" is the
end-to-end command accuracy: both heads decoded jointly over the 31 valid
(intent, slot) combinations.
Saves the best model to models/crnn.pt and the training log to
results/history.csv. All plots are generated by evaluate.py.
"""

import time
import argparse
import csv
import random
from pathlib import Path

import numpy as np
import torch
from torch.utils.data import DataLoader

from dataset import VCMDataset, load_labels
from features import load_intents_slots
from model import CRNN

ROOT = Path(__file__).resolve().parents[1]

def run_epoch(model, loader, loss_fn, optimizer, device, combo):
    """One pass over the data. optimizer=None means validation.

    combo is a (31, 2) tensor mapping each label to its
    (intent index, slot index) — used to decode the two heads jointly.
    Returns (loss, command_acc, intent_acc, slot_acc).
    """
    model.train(optimizer is not None)
    total_loss, correct, correct_i, correct_s, n = 0.0, 0, 0, 0, 0
    with torch.set_grad_enabled(optimizer is not None):
        for mel, intent, slot, label in loader:
            mel = mel.to(device)
            intent, slot, label = (intent.to(device), slot.to(device),
                                   label.to(device))
            intent_logits, slot_logits = model(mel)
            loss = loss_fn(intent_logits, intent) + loss_fn(slot_logits, slot)
            if optimizer is not None:
                optimizer.zero_grad()
                loss.backward()
                # gradient clipping: RNNs can produce exploding gradients
                torch.nn.utils.clip_grad_norm_(model.parameters(), 5.0)
                optimizer.step()
            total_loss += loss.item() * mel.size(0)
            with torch.no_grad():
                # joint decode: best valid (intent, slot) combination
                log_pi = torch.log_softmax(intent_logits, dim=1)
                log_ps = torch.log_softmax(slot_logits, dim=1)
                scores = log_pi[:, combo[:, 0]] + log_ps[:, combo[:, 1]]  # (B, 31)
                correct += (scores.argmax(1) == label).sum().item()
                correct_i += (intent_logits.argmax(1) == intent).sum().item()
                correct_s += (slot_logits.argmax(1) == slot).sum().item()
            n += mel.size(0)
    return total_loss / n, correct / n, correct_i / n, correct_s / n

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--data", default=ROOT / "data", help="dataset folder")
    parser.add_argument("--epochs", type=int, default=50)
    parser.add_argument("--batch-size", type=int, default=64)
    parser.add_argument("--lr", type=float, default=1e-3)
    parser.add_argument("--workers", type=int, default=4)
    parser.add_argument("--patience", type=int, default=5,
                        help="stop when val acc hasn't improved for this many epochs (0 = off)")
    args = parser.parse_args()

    torch.manual_seed(0)
    np.random.seed(0)
    random.seed(0)
    if torch.cuda.is_available():
        device = "cuda"          # NVIDIA GPU
    elif torch.backends.mps.is_available():
        device = "mps"           # Apple Silicon
    else:
        device = "cpu"
    print(f"device: {device}")

    labels, label_to_idx = load_labels(args.data)
    intents, slots, label_map = load_intents_slots(args.data)
    intent_to_idx = {name: i for i, name in enumerate(intents)}
    slot_to_idx = {name: i for i, name in enumerate(slots)}
    # label -> (intent index, slot index); used to decode the two heads
    combo = torch.tensor([[intent_to_idx[label_map[l][0]],
                           slot_to_idx[label_map[l][1]]] for l in labels],
                         dtype=torch.long, device=device)

    train_ds = VCMDataset(args.data, "train", label_to_idx, augment=True)
    valid_ds = VCMDataset(args.data, "valid", label_to_idx)
    print(f"train: {len(train_ds)} utterances, valid: {len(valid_ds)}, "
          f"intents: {len(intents)}, slots: {len(slots)}")

    train_dl = DataLoader(train_ds, batch_size=args.batch_size, shuffle=True,
                          num_workers=args.workers, pin_memory=device == "cuda")
    valid_dl = DataLoader(valid_ds, batch_size=args.batch_size,
                          num_workers=args.workers, pin_memory=device == "cuda")

    model = CRNN(n_intents=len(intents), n_slots=len(slots)).to(device)
    n_params = sum(p.numel() for p in model.parameters())
    print(f"model: {n_params:,} parameters ({n_params * 4 / 1e6:.1f} MB fp32)")

    loss_fn = torch.nn.CrossEntropyLoss()
    # Adam with suggested betas (0.9, 0.999) + small L2 weight decay
    optimizer = torch.optim.Adam(model.parameters(), lr=args.lr,
                                 weight_decay=1e-4)
    # cosine learning rate decay from args.lr down to 1e-5
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
        optimizer, T_max=args.epochs, eta_min=1e-5)

    (ROOT / "models").mkdir(exist_ok=True)
    results = ROOT / "results"
    results.mkdir(exist_ok=True)

    history = []
    best_acc = -1.0
    epochs_since_best = 0
    for epoch in range(1, args.epochs + 1):
        t0 = time.perf_counter()
        tr_loss, tr_acc, tr_ia, tr_sa = run_epoch(model, train_dl, loss_fn,
                                                  optimizer, device, combo)
        va_loss, va_acc, va_ia, va_sa = run_epoch(model, valid_dl, loss_fn,
                                                  None, device, combo)
        elapsed = time.perf_counter() - t0
        lr_used = optimizer.param_groups[0]["lr"]   # lr used during this epoch
        scheduler.step()
        history.append([epoch, tr_acc * 100, va_acc * 100,
                        va_ia * 100, va_sa * 100, va_loss, lr_used, elapsed])
        star = "*" if va_acc > best_acc else " "    # * = new best model saved
        print(f"epoch {epoch}/{args.epochs}  train {tr_acc:.3f}  val {va_acc:.3f}  "
              f"intent {va_ia:.3f}  slot {va_sa:.3f}  loss {va_loss:.3f}  "
              f"lr {lr_used:.3f} ({elapsed:5.1f}s) {star}")
        if va_acc > best_acc:                       # keep the best model
            best_acc = va_acc
            epochs_since_best = 0
            torch.save(model.state_dict(), ROOT / "models" / "crnn.pt")
        else:
            epochs_since_best += 1
            if args.patience and epochs_since_best >= args.patience:
                print(f"early stop: no improvement in {args.patience} epochs")
                break

    # training log: accuracies in percent; "acc" = joint command accuracy
    # (intent + slot both correct) — the same numbers as the epoch printout
    with open(results / "history.csv", "w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(["epoch", "train_acc", "val_acc",
                         "val_intent_acc", "val_slot_acc",
                         "val_loss", "lr", "elapsed_s"])
        writer.writerows(history)

    print(f"done. best validation accuracy: {best_acc:.3f}")


if __name__ == "__main__":
    main()